---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: python-ide
spec:
  encryptedData:
    postgres-password: AgC436Mt9ReEtJ9yww+5rDkyEJPbbj02aIZeZeBzXZKpICQgRT0A4ZZXn7av8x8F5rs2BYxvhLexpUQi+2UdJX96a7Yk4of25F92AxvvfgxIpsD1LkAlKAG+skji6UJ1OzOea5yvdyVZAdLESfBIDykg16z7u79BtQ3SibnjOT3Go8eyTUKwUIIpBFttWbaIFG9Cn199wu8/pI81PnIgh7H4w3bRfE1bnydT11S7F09N6xOvDE92W++aKplRnWcOSBdeScxMDa9OeFmTtFDFB4alnyk+2bvFfCm72DYPB4SossZlrGmo264sI/rTTHeDrnDOIzU0fhvTze343ZRAXwIg+yRV8UoiJSFy6VZi6ej3keU54lOq0lk/8BlolMH2OTT2PeEcOYigKfLC52BvKlElyHyleSi7fypoGygnwAhEq4HYQwTium1QceWe2zZ7cbdXgl3xCoZK5oPwgNGN6YCNmrxfedNOBp9zfFh13t4yGI39AHW3Nxo881YY1k/i2rLgcsUC4ozUWN6qWHIjAmk4GkTkXJgwmnVpBJRNK0053zXsCTjsXlyG4lmsS1oMe6ZAeo95zeamCRWBmRIAkFOnrVqZmj4MSTHXpauIW0LoBFbfVkUKZCX7lUoYXm7Ijz3Ia2jujfq/8PfffGwQJ5b/rSZtAGPeqn1rNY1ocklF+rewQb70XMTWgCafa65l3KCDCNybcA==
    postgres-user: AgBy5WWc5d3bi5zphRS/Uavq34MKAvnW6ugI2rXF115dmb0y+IVE9cyLh5HolpWHK/nHgAiJp6zQsBJ2qd52RC37d9QXXdn+o/QOpp3pQXTyOFqFM2FUFF4CXxgD2MLaEZFHVKWfuPktqEPt/l4XMg3mmpA8ytu+bl7sFIMNKKpkQpl45NpwCvExevIN+Rb+EvZZpr25k0h4yj4B05HTaCi+N61DYLiyOl/YLddMY7Ub2SzMfFQvNKsLxAVV8XtQg/HyaLCEc+S9z6kLpaXqKMK0aHGXlwGMlBdKsTz/GLMMhAzKFEmkc7u3RygYKcIYy1Zs2C6efKTYdwPNRARuMfxFJOfdZM4g7Ggn4ZrmNfQqR9wDjFEmnUPyySAM+OsXTAhSzbavBL7Ux3VlgUF6+UqzQHUymIrw4+zEUZly9T5LGN+FlD6EUucVE57mNnplZZuAWTvPIbRJBAcpAuG3ndP2XwWj6radKRpvPX8qvRMJ6nOS4s3ZJc5MtlHszDbi1APuYWsPbdgP5psTj84MbM0yTogchAJ9HC8E6xo6z0XbPpr8wjDU6yaRtTC/fP71AeOgBwWGG36gPl/JiRUj+HDS00Wz9sj/WsbyUtmhzLC+VScX+rcqUftO5BJetOmBpiI4c1aCE3dc83SK7dAH6vXWnLMdWnZ62g+j1yj2sJndi7D5bzWyRglW4bFPbHz0UjSx7UqrFQ==
  template:
    metadata:
      name: postgres-admin
      namespace: python-ide
    type: Opaque
