apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin
  namespace: python-ide
type: Opaque
stringData:
  postgres-user: ENC[AES256_GCM,data:h1Mu0e0=,iv:eId6Rj0jXr5F0onGilYT9VgnVq9ThuPWOAIV7e3zbLI=,tag:+wFSAH+SP9fBGWSHOfTV3g==,type:str]
  postgres-password: ENC[AES256_GCM,data:oPN0Rl0=,iv:XpU/146M4gW+nX1BQ6+579AgcZPIJFrgTOomxXjZLP8=,tag:TguLbME24p2MMXc4oCOVNw==,type:int]
sops:
  age:
    - recipient: age1uxgxf4qhk0tddezdfvwgjtsjukc6d7laezlutml0mxe69apmvuws8qkqlx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMUcyaE9XUlJKanprc01o
        S2dpY0tjZ1U5Z3VObHZMWENxRUx3OUVuOG1nClpmdzZBa3hsd3lNaHAxVi9tR2hn
        eFlSSlVUYXVhSWF5U2xudkhXN0pMRjQKLS0tIE8wL0phM01LeHYzZWI0eDIxcFJr
        UU5jMk9SRnJvdmxYOVpRd0xtQS8wQVUKisxXr6sOztUg54id3DL7jAuXIK9Mi74d
        Cp7PE0PqrRqFyF9VxGiIjG3jwk4WD5Wldmak8BMA7WEfTJkvokA+VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T14:22:19Z"
  mac: ENC[AES256_GCM,data:C8NNveyV8VmUNTJzOqDvgB82Y33Ui2EMnDeXB88RVqdVlQrrho8baPRIAgVRVyRPFVYZ+2R+26Fn+ku5a8S0KOkztpgaZutTc9Tju79OxY/VY+AHKQygVq1Tt8+Hvfw/R1H8BYj1lPwdGg/8M2ZUUB1nJBL11tmSbB1HfyGDEBc=,iv:BN7zH1IJraXJnAJ5B3SF4KiVJfzgYZNKOyW5hq7bEWY=,tag:YCN4Hz4g/ns91telwq+r/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
