---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: argo-events
spec:
  encryptedData:
    rootPassword: AgCu2FGcHjGZ5xuTGjTozmfEdoeRydvTYgnCbnE2WhEG9dnNg6ayrxfmjokU2r5t2m98PezfhbruFYH7yHUGkkcodMbhnoUhKangqIGfauE+H27Ben/ZHYTpA2OFnEFKpTTBmTnGS+4tEtpi2I15xX5ZgpJL638pb+75nbrnWmiv6IzJRgMNhQYk+nBVCa0rdpaYiTrLoiSlb/ZkSm4GbV+GpfODXyZt3r000eaueMxLgXGVDYrHS/jyANQlmTqWIrKyKdzSUHBHRNnWz8ZKN8kGTY/dTLBZxlIjKhyYJZXtab6637Hlzdlpur4PsbcboUZ1CAimPrG3ZEhjn/I9Udw5fq6olh3ebuoOsinkSoqhTU/dkARaJgiz9E1Tobxhk0UAXj4WzJGBBqwKZECz5BA4dfpaQfDXEFhHEmIWwCiRpxdWCzee6LtnR+VGxTcdXt26n4ZFhC0W1ZYo2kUPD8EJCFUIzewrkKB4PWa/t3g8kyFIu8caKAj5tUw+GyGyACIIoIKFnuW0ok55itcvI80RRShgk6DKaZgcyTK/r48CgzFaRxF5iQErQy3ZSI+ZCgOtJioDKBz8395GZV0ktAkNL1AYrQG2NYU7gEg/WGsuLThhoc4dMqJCgiuW40PVLhlJHf8GjlF1JJQxrqC4n9MwvtJWBjntMkfd0uuQeRqkc+vPe7LgT4iKwNk8WCx3mTSNTm/Os3+WZw==
    rootUser: AgCT0lpLT+aeWTcYzbE33a9YZDyrbfAzBbWh6Lc94McKsO7VjRAtBoq33/HJ4Mr6/JLcarHsjoZmBVpSgVRdcj9aB7DWlNSZ5kwbvjfgoDzxQDUeoiI0D+yu30xBV36Q0MORP4GQtd1fWcUVaVhAoFEKF2whms+dBeyt1KiNb5Ie/Sq2DmBBSf3xzEa/yjEHVaVRnJc1mVi32CFaPsSo+5W9hdbWMtR96JltKgBHVbtvUy2BoP9QLxhvPd7AveikVO1rz9jAaIAP8jeLQRyFo2AJLrPdaUP4+xJwbxK5QLgGQ3BLkSuHnbVBKL2sMGyhzDE7CEKz8QTJAnuTWD/vXGtyX898J79HjP7ibhkK4N6R9sEnbOIONjsttctvUwHUwyqSaaJZblvN3fP7EVv+XFHAjI3EuuRwpqgrTufpjqFI3StxUNYbTnISXtl/Ne/x4SA/CgHeP0N0lqBLNTHexzpwErSymzEXhHd4CLfKSQH+FGRyFJeWPhI7LnHmenk05TylajHz1FbvVI2tLFf0T61H+fBthe4H8DcAkSfTW5Fc1VCwzVOht1KUacEBjoedWzAUF0EA7D9ZLq6b8EQH7q84Qk/jVMb4E5T9QySzzzxj2Akbo1lbSG/z0b3fasnr0+haf08q7qGZxAL3EsYNxlZOh2V4QfrDgr+w5SaYHQbaIAbEBK5U7uuFjSXuiKypUbWvly7CeUXE6vnU
  template:
    metadata:
      name: minio
      namespace: argo-events
    type: Opaque
