apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: oci://quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $values/helm-values/cert-manager-values.yaml
    - repoURL: https://github.com/noah-w24/ml-engineering-cluster.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true