---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: argo-workflows
spec:
  encryptedData:
    rootPassword: AgCdgPpgY3oi6now0GyyvQ4bRQMg1fCxLRdCoYCSQsO7F1BOTcK8EXCM0yHOpkY0u9ApSb1lkQvfhzIQVQv76MMdT3CRsBKVRYymbCLsVHx/4AolCc3htxWyPCOOPKYFvMHlMiVjHUDOpuaZQkRJLBMcH6Gz/79Hp20DkkuA4HVb9VgVe5Aug7leAjLE6Pq81PUVD67JbrXSbhvNO1sS34nyeHV/tdD3AEPpqk2yZC62/6xsn3FmUTsIlHjBg9GZoNFClAf2zKvprdtLbvMYVoutgU6DuBQ78b86EbtSTloFIIcIpTxQuKllmQizilU+Wg8J79BAA0hEUP13ERsJnOE5Z2zcM9Kmth7CdqwmkeUbF+bDqkSzGWLzvkxicivxKECS+kyXQ7dRZ96CSU1l5zpMemlww63PiU40DSgRrCHFAvY0mbZAvBp/zHZAyhvJRhIy1aICtEyPDxWRpd2mlpvl62+Hz102EiePYwyY5lrkNBUR5mCirTdVjSDw3p4A3Lwsro0H9AiSUOkSOmNT1c1oz7Eq8NZlMiErSDMF8bRF4VXBhSxTldAutmy/+RYWCXRuBVbqO6nr5HDCb67uHuOwbWlaLAXcxDBBuiSxl8tuuw9gdQyEli+JjwdleWe3sZFzOgkErF+1jNxRE3eIx/p/8YrPF1JVjO4NvZIoVtRE435NWAZ1HjMOESS2ZRC1P55Dk8dTSLyFrw==
    rootUser: AgC5sNSstaKJ4QiIFQRy3iESFxawouXM3kLCvWvMqUcj4VyF9cV4L3Usv4sLBvW86nn+0h0CPDw1LoDEV/AdjXg/0vG/oJWOk5W4VYcx8ca8f3xthf65oreTMALOqRoFzb8GoqwuH111BSTxvDEaTUp8+TCxEOS0gcXg++kTjF4lc7iwb4NzNXDdzryiSvoUiJSTArw1UfGOVWk8FfriCbBKfoGIVYVqr7iOT0zMCBxfH6aW1ss6UDCtR/gQO4mWaq3OGeH9MWRSEEZaaPcVa0T08Nr6NBknLoUlnYfG1wyAjvOj/oBdTWDPpb7rR2sCGZ2iY62K30C78k+81SK4qyAS6WQK/IHR2r3XArDFGgZj2QruuQLRNkpTtfG61l4IsqQPNyjiEgN0Tt9K0VaGERtLJuQ3KCGEpM/yyL2hmiRzOYYcd0roGsgKeVGXtybBRPCJW+XSRZB50zEQxvn2L4KkZ8f0j9LmByqly6nYbRY6Fj5ObCGfQ4j/zERjIbsO7VVOWTVCzndClDNfNxKZN43J2rs9i/jl+6b16fVM8f91kt2G1WCyOMrhd0C1bczyUzorQIm0Tv8PvOrwlseUoJQdorGDZI9B8fdwVfGKZCm2/YO+7fq0JFVxYX9m/nVFn8bOP2tpwWsJAzYX6rVmjijG4owqclW62MLGyPvxUZlb5wCbOn+evkCFw5avxEOs4Z4GHbh+zCjukuya
  template:
    metadata:
      name: minio
      namespace: argo-workflows
    type: Opaque
