apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: mlflow
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:WkeQPg4fmtGC/g==,iv:SlLPyRs+ySVcDggFA1ZCwVs4LMFqv49eBxADdLRbOj0=,tag:ey5u8rXCizWR6eRW2KzjNA==,type:str]
  rootPassword: ENC[AES256_GCM,data:au9TKaafIXc=,iv:AEDIMoqUrySKC/E2CNAuO2ryNCTNlJXS6QvfvgtCII8=,tag:ne8bXCD15mHv9oaqOKuTVw==,type:int]
sops:
  age:
    - recipient: age1uxgxf4qhk0tddezdfvwgjtsjukc6d7laezlutml0mxe69apmvuws8qkqlx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOW9GREJsZ1U3SFp6S1ZY
        cE9XY3NndFBPUzhEU1FmTjNuUVYvSk0vWkI4Cjg5MGIwTnlQeGNGZzNNZEE0WldQ
        a2srSzN1b0FlVnRRazJZMERNUWcza0kKLS0tIC9ydmRUOHUvOThtOFFueXlpL1JE
        U3Y3NEVqdnhUM0l1S1RWWjBsODF6U2MKOwiOU3UPdYKGdm9mBbVE6k1fUzshU4tQ
        9HitZIJFYZsTL5w7VGFRWddhW1KyrnhGhBMRsvERK0TYHwUzdL2GfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T14:22:19Z"
  mac: ENC[AES256_GCM,data:nZgjtwhaI6uYGjA0k+krvs7dE31VKdI0iAIxqC0aaBnu/89zc/62eIKWmfo4YrEpTpDTxcDlRS2bC3E1r4/flypgVt2N2BN8s6BG6lW47ow5tsgOdydPnRettwaGFjEhmOKJ3RSbzyQ3StvHQWGz5r32Rer8t9rQjQYUsXiWDdE=,iv:0Fm8f/o5yQykCFuePSrxTRZe72lcSdISosOa+9BxRSk=,tag:2IF5pnwyTPKuw2c8q5ALbw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
