---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: data-storage
spec:
  encryptedData:
    rootPassword: AgBivOk/XNjZoucG8tMeymLfm39e7kj4mQF4kM1bkkMMiWkoS/xYSc1MM154vaASDB/oisfZa5D2BgiCXKjBXQRCyvC25U28/6GnTUcgnoPzfZJbDEtkN6Ed6Oc7kBD7sxtJ6xyziv0dUXNep9AMtsbDdBwq+pMT7Rh/z1ad6W9u5+9hRgBVwTfSwhrC8HDGfw6KZW1uudYDybSomnqeiMH2L0KSqO93So/MLOodajMVK2WvlXW+RypbP5kHuBfSBq4Y4TdUdc9EXg21YIsfvBlxAn/y9WXS4Kjh4dgRxNdpP3C6pkYVWXgkc/BN+WViGe620MO02T3FG6DiF0LoXNB/xc7H5sxuRMJmXEPMd8dFtncoY93HIXJ93WOrubT96ahbxgbh7DVLdy2oKt++76vL6J91GoSP+oUbSE2N4y7dnZB1rVFrE9IoOWOGw7x24DUAbHgS6b88+D/UE2unWqdONd5NSP8vCuAWAh399aLWGKSEJwUNOHEiEMSmDjupyERKycadllOuaHjQgD6WwzSR2mWhECrIkfnRFq+CvjTs1DUFMH0sqqThbQHs4d8j/u+XGhI24Bi8ieSi53VCI9ADU+d0g+2hyQsIe4wK6NR9dfpP9DWCtdeYcw2CNn+1FqhEQcTLP4jrwenAxb8T8ogu4Dnu1ZRxtMT8BIygzuZj5T2ZWQgs7SNXkTz4PEMwC8Kqrbp6JY1teA==
    rootUser: AgAwuvmbIaC+kpy/n2IabqRjPLyG+I88JqL8orJ3YuE7XXcGzHbB8YCEHiSVpjgMUBXZWwjsIis6bfG+tavt9IiG/LnhRxmud9LLXaL2XwzNANhNjKo6IMNEAXRJX9HyV9665RTypRztHMKo5TA4n/bb5M1O6S/tm5Viopal3L2W2y+WgwkGsTaqDtCsA5NI1f48aZXpQ43manheMpcS88zmNxmXpwfhwCm4nTUmZf6mDeuZbxRrJPpXFxfG3q7+FEFj2SHXNfun8ouDsx9iRqANtdI7XAr1P32An2JPG7Jr8oU4t52YfzcZZvDuNBk+1fYqZwrZiVibA18qhVC4UPaEaVNJpHTgwgKKP3zqaMc6kP9uf0oAbNVip+92gEiP0iKoikjZ8+SUfHNuj3t1YOmTBNdknW6cMq95ch5o7CT09RfycSiPDGmqDToOlxW2gPpJPGxMIH1z+sljkGYFiubiqbHkgia0ynlJsqT41rEKYNzUrJvYEIHW735/EjrP6xaKW5Z2bP/1wSLh39ZYi1dLIJV7xxIn1dJkBf2zJpfyRdNb1997Z3ur8p0kd5nV8OEfc3wQFnBbGtPQZPt9QutBNrym7aD1nuJmWbAaH6p8xs+OAvpEXawjmVBVAGMRc9QukS5YjUVkNgg13GG7wL9kLsWNDvDCIBtjcyDNdBY2BDfyagy4nlQPDEoDCVQyMG5UklvqNm0CSJEi
  template:
    metadata:
      name: minio
      namespace: data-storage
    type: Opaque
