---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio
  namespace: mlops
spec:
  encryptedData:
    rootPassword: AgBZqT2Jd2d4xilaJZKihRqt48HZZWsKpEzQO9kzhraBYmB7Rf/Thr3D8uCjo/bAyJku1aV6Z0kld5epyVPiyeLQFiCNMYjLygThZeiJ5tg5qbmNYDDaqq+ui7B4Te3qroOk1Uft4MWEfOJEqMAVzT1jn1ovdghopFByq1eAhqKXj9IzO3Vw2yAO+Z1DmWk55+kFXCnnRmOk7U2SMlya76I1yAGZPcW0wOmT50LYZXaavU4meikdc4b+1S7cuS37KBSwN0qVx9ySA8TRDoS73V0u7Y+9jG/HSbeA0hLJdrEUFitr8hp0ftuhxJp6B2uTaL/YtKUyZ8Y/hUQ09JPL/eQ3Z8cesI2dKuBF2DYpJvFMPMF+Br/Epdmj43q46UVZkzmQBpDV2+G1Fyy+1E7UedOnGJc7UFBuBwV00/wETn2DqPc+snLJybm5D56U7MCQXykJGBjX3tFpw129gjcif8HGIlW3b1KAqvFXCV2z5Wf1uvzQziH+G6nlTuouqS3TDTR0zvaUX2q1rBEUnZEaAhZ3PfMqrScAl5uMTz4IFGBFaVUO00ScEGYJSMFyhiN1Gr+l/kqL9QKPlpcy+w1fzn0Vfdb+KMDMJNXbIxMX3JXSGFTLfPtLfs4mf6rChMxXyMFjA/sH8zW0sEvozsyWX8LTIxP0okC++DoYj/DuhgGgY2Rfy1xsKmIWOGBS+b903PxqFfKnMAyCcw==
    rootUser: AgBsfoghq9UtZ7fUHJxH/bfwzPKeheahUsmlZBaxvc6P37yY3fjQurQrK7sfBsPW/P3c3x/U3NHNpBOl93zJA14WiBvUmHD7UWqHlcVQTCail6ucB54fMTdnyBicPvEe0WKIu60k9NoyXGBMC7KfpdY3i2QGthboWRTdnA3mQH9aswx0JlSNSx+2GyXz90/citXpfrX41+feEMbfK8lAmokdnHojRx3wg6B4Xp355HHoOkIiFJrlSBKM4yfiO5LCZ9fJqLL0h8GwjO6tyMzSNG5m1lOjlRv2k3ZH2PPmTELAHQzYJyCXEVjWK9AEeERoDGAuUhFo0uTbLGCFv++EJXVuwRmOQa8y6+kwQ9QsRdT2PtXlPq0DCnIERkqYQ5TL0YS36XrtWeGYdIB0D6uOlphbWae4fyjca0CcXxmFCzyrL71nqTUJyoOsJEOOcXvmlnx24dNAkP73PcYZyqwx4lGBb67DrIySOSeQw0SgEvy1eQjKAtkFMI1t530VAhsDGj0GpdJkG75ua+UlmD8epADPPDc5qQOvkVD4U/TofQcugXVNZgOU4LrDQKuuBxwwXGnhL6BCvVKZjSzQ95aXJA4Z3VwD14U24JQYWqDlk1NcyEkKHZ150tiwCiRhP2STbWlc0FcoC5AKtK3xGYof0ybhYTJI0rpny1Cf8/HYfkBnVHGzzMfAQ75o5g2N0CrYPe2WhYgKsHJOheTm
  template:
    metadata:
      name: minio
      namespace: mlops
    type: Opaque
