---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin
  namespace: mlops
spec:
  encryptedData:
    postgres-password: AgCb0zZ6NO0KJNKlFx4Hw7ixkR6Bhpbc3HifDYkYMjC3xT4i97txe9aVhprsiOdAT0OGCdoGNMcV0swFzNOduyys5gjV4M9J7cm5tM8Pv2lNCH+yRc8+I+PPrQP1wLOn4spkQonbWbwjzuKDTtcWRSBDPIpRvsrgKBdxjnzr072tNnl50Cet1Tabyr06J8xV7wnHf6ZK0vFtfjJMVaRL/44rKT6Lb7rF+DdijsWbeuMpjX3CFo0mrk6wOpYazuMVmqEbP/y8znYNQe1xRgjZNdbfCHx6eMHtDdJ3lm8LDvZdMc+skX2mN9lK6qCZ3HcBNTRsK/mTsF2+tWAgBJbJLBXq5iPGHRYC4OK6f7WBkLiBFQVBW3OU2DF0t3lP2z8I6LW0+IByGsUKnGGA0vRmDNJgFtQLj5rBJgjn4liWvq0PiNGaEk7DkzRvhZGcVoxL8bAdjahUNPJIq2DK53fcTlcPL11e9WGMM353Kqtgc8WiHzPNdl+wiBy/Iz22cKKU+Ko7aotvypgM3U1vpvtLqqwXlrBkqG8jvbY/0P8cu4Qkylo9e10thg27nAl7qm61rOzmBXlnKIQHtzh2XcFaC/f+kBRkvqoRdnA7nVrxQrcBkpK5vp0opMDZ7+YdZUiH6PEAfkkx6rJ/42i2+suvFMKMw9/mjqrp8U4qFY3igw6dxSViQg26O1ni0qmSHFrhFqTeTJ2qOg==
    postgres-user: AgBY4lNTvh7a1aHA4mJOJh19LyhQl8izai2Kq8AwZ31uUg6NDcYgoF39vppDyOgaGokXVjjqDBV0/1TyNqk2IrujY6iYt6tmwdH7QsG4qj9JvL+VX40E4Ra53KJ0eB1yn3U1XFLHQjApz+iz33toRoJYh1mBVIAnnif6TP39aqqMwjMuY+/YhcKWcwASCzJC1nJV+Q83U+Qyp1sSZkK1qRTKtLjPwgbwq+oJdAYbZzlra8/3Gszst+3zTOV8eQ9IDrWOjWKt1l5w9SLdyrCXyWfcA//g8ac+czOees7KElvrgSAVavAmrYi9r4DnnU4F4oqRIbPPfIod2w/pVN3jIb5zzAO31KBkKF2CTudL7Ck9ARWM1+7UF8kwjgcCbkbo201y7xVWK0l4OQqHlFDhbbKHsa0fm95yGKgp6s+K8sp0o8qitDMjW6YC4PMb3nDC3ldaSG5fRQHTZpBPvAReUv2wXJICk4K3TdSijYDCSycYRiR0NkZeA1g3daGWMo2IEJMA9+hesBAvURD/x537DGS6qSRV2TyDrlhaPXjqR/XMSLvazlIYAfV0NX5R2oFMPjoqa2BjkYVsjMgOs6vOU9pE3xHMaQOLd4qR4rUjVc2YlcOND1UcldoT8j3ps8mvyjxakJRhtqgxtSDxu3KfHvLMTWbB/HLfmwZ+2En/fKjRIpvRnxS+8VxRbtFgtroCN4l3x4a/Aw==
  template:
    metadata:
      name: postgres-admin
      namespace: mlops
    type: Opaque
